### PR TITLE
Add customAuth API (#61)

### PR DESCRIPTION
**Pull request by kirillzh**

### CODE REVIEW

**Comment by kirillzh** [comment]
@benjohnde, any chance you could take a look? Would love to upstream this change 😄

**Comment by benjohnde** [comment]
Hi @kirillzh, sry I am going to take a look on Monday. I can also prepare a release afterwards. Thanks a lot for your contribution :)

**Comment by benjohnde** [comment]
LGTM!

**Comment by kirillzh** [comment]
Really appreciate it, @benjohnde! Do you know when we could roughly expect the next release?

**Pull request merged**
