### PR TITLE
Feature: MFA

### PR DESCRIPTION
**Pull request by gaebel**
- Adds mfa routes by @tknoelle 
- Added more routes
- Fixed test

### CODE REVIEW

**Comment by gaebel** [comment]
@tknoelle @benjohnde @Ingwersaft Would you add a convenience method for the qr code generation, or do you think this should get handled outside of the library?

**Comment by Ingwersaft** [comment]
If it's not too much work getting this done here it would be awesome to have this :)

**Comment by gaebel** [comment]
Just looked into it: there's no multiplatform solution for qr code generation. We could use https://github.com/g0dkar/qrcode-kotlin for jvm and android to avoid depending on zxing. For iOS I could create the qr code with platform calls. For js I'd need to import an npm library.

**Review by Ingwersaft — APPROVED** [review]
LGTM!

**Pull request merged**
